import Head from "next/head";
import { ThemeProvider } from "@mui/material/styles";
import { theme } from "../theme"; // Import your custom theme
import Header from "../components/Header/Header";
import Hero from "@/components/Hero/Hero";
import QuickGlance from "@/components/QuickGlance/QuickGlance";
import Experiences from "@/components/Experiences/Experiences";
import ContactUs from "@/components/ContactUs/ContactUs";
import Footer from "@/components/Footer/Footer";
import FirstImpression from "@/components/FirstImpression/FirstImpression";
import Reviews from "@/components/Reviews/Reviews";
import SearchTours from "@/components/SearchTours/SearchTours";
import PostHero from "@/components/PostHero/PostHero";
import MiniReview from "@/components/MiniReview/MiniReview";

export default function Home() {
  return (
    <>
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ThemeProvider theme={theme}>
          <Header />
          <Hero />
          <PostHero />
          <FirstImpression />
          <Reviews />
          <QuickGlance />
          <Experiences />
          <MiniReview />
          <SearchTours />
          <ContactUs />
          <Footer />
        </ThemeProvider>
      </main>
    </>
  );
}
